=== breeswish/hexi/plugins/input_flight_attitude/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "text": { "type": "string" },
    "order": { "type": "integer" },
    "fromState": {
      "type": "array",
      "items": { "type": "string" }
    },
    "attitudes": {
      "type": "array",
      "items": {
        "type": "array",
        "minItems": 7,
        "maxItems": 7,
        "items": { "type": "number" }
      }
    }
  },
  "required": [ "id", "text", "attitudes" ]
}

=== breeswish/hexi/plugins/input_flight_attitude/attitudes/attitude_take_off.json
{"id": "take_off", "text": "\u8d77\u98de", "order": 0, "fromState": ["initial", "land"], "attitudes": [[0.006699999999999706, 0.0008, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.061699999999999866, 0.0008, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.10769999999999968, 0.0008, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.15769999999999973, 0.0008, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.20769999999999977, 0.0008, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.2576999999999998, 0.0008, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.31369999999999987, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.3586999999999998, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.40869999999999984, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.4586999999999999, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.5096999999999998, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.5666999999999998, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.6096999999999999, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.6606999999999996, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.7106999999999999, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.7606999999999997, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.8156999999999999, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.8616999999999997, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.9117, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [0.9616999999999998, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [1.0127, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [1.0676999999999996, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [1.1137, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [1.1636999999999997, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [1.2136999999999996, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [1.2686999999999997, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [1.3196999999999999, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [1.3646999999999998, 0.0009, 0.0, 0.0001, 0.0, 0.0, 0.0], [1.4157, 0.0131, 0.0, -0.0007, -0.0003, 0.001, 0.0], [1.4656999999999998, 0.0112, -0.0002, 0.0011, -0.0003, 0.0025, 0.0], [1.5156999999999996, 0.0113, -0.0001, 0.0011, 0.0002, 0.0038, 0.0], [1.6006999999999996, 0.0118, 0.0004, 0.0007, -0.0001, 0.0048, 0.0], [1.6186999999999998, 0.013, 0.0, 0.0001, 0.0001, 0.0056, 0.0], [1.6686999999999996, 0.015, 0.0, -0.0008, 0.0001, 0.0062, 0.0], [1.7187, 0.0153, 0.0002, 0.0011, -0.0002, 0.0069, 0.0], [1.7707, 0.0167, -0.0001, 0.0003, 0.0004, 0.0074, 0.0], [1.8227, 0.0179, 0.0004, 0.0006, -0.0001, 0.008, 0.0], [1.8717, 0.0201, 0.0001, -0.0004, -0.0003, 0.0084, 0.0], [1.9216999999999997, 0.0202, -0.0002, 0.0029, 0.0002, 0.0093, 0.0], [1.9716999999999996, 0.0218, 0.0003, 0.0013, 0.0005, 0.0099, 0.0], [2.0317, 0.0229, 0.0005, 0.0017, 0.0001, 0.0105, 0.0], [2.0797, 0.0294, 0.0002, -0.0056, -0.0003, 0.0104, 0.0], [2.1307, 0.0206, 0.0, 0.0086, 0.0, 0.0124, 0.0], [2.1807, 0.1159, 0.0001, 0.0065, 0.0004, 0.0116, 0.0], [2.2306999999999997, 0.201, 0.0003, 0.0142, 0.0, 0.0097, 0.0], [2.2886999999999995, 0.2807, 0.0, 0.0266, -0.0005, 0.0076, -0.0001], [2.3316999999999997, 0.3586, -0.0004, 0.0406, -0.0003, 0.0058, 0.0], [2.3827, 0.4205, 0.0, 0.054, -0.0002, 0.0043, 0.0], [2.4326999999999996, 0.4755, -0.0002, 0.0647, 0.0001, 0.0033, 0.0], [2.4826999999999995, 0.5283, -0.0001, 0.0732, 0.0003, 0.0025, 0.0], [2.5336999999999996, 0.5797, -0.0001, 0.0801, 0.0004, 0.002, 0.0], [2.5846999999999998, 0.63, 0.0003, 0.0862, -0.0002, 0.0017, -0.0001], [2.6346999999999996, 0.6809, -0.0002, 0.0918, -0.0005, 0.0015, 0.0], [2.6846999999999994, 0.7303, -0.0004, 0.0973, -0.0002, 0.0015, 0.0], [2.7406999999999995, 0.7794, -0.0003, 0.1029, 0.0005, 0.0014, 0.0001], [2.7856999999999994, 0.8284, 0.0007, 0.1086, -0.0003, 0.0014, -0.0001], [2.8366999999999996, 0.8775, -0.0015, 0.1145, -0.0002, 0.0014, 0.0001], [2.8866999999999994, 0.9268, 0.0015, 0.1207, 0.0003, 0.0014, 0.0], [2.936699999999999, 0.9763, -0.0001, 0.127, 0.0002, 0.0015, 0.0], [2.9986999999999995, 1.0262, 0.0001, 0.1335, -0.0001, 0.0015, 0.0], [3.037699999999999, 1.0765, 0.0005, 0.1401, -0.0003, 0.0015, 0.0], [3.0877, 1.1274, -0.0006, 0.1469, -0.0005, 0.0015, 0.0], [3.138699999999999, 1.1793, 0.0, 0.1538, 0.0001, 0.0015, 0.0001], [3.1887, 1.2312, 0.0003, 0.1607, 0.0001, 0.0015, 0.0], [3.2497, 1.2836, -0.0001, 0.1677, 0.0004, 0.0016, 0.0], [3.3026999999999997, 1.3367, -0.0001, 0.1748, 0.0004, 0.0016, 0.0], [3.3556999999999997, 1.4067, 0.0004, 0.1843, 0.0002, 0.0016, 0.0], [3.4056999999999995, 1.4616, -0.0002, 0.1913, -0.0004, 0.0016, -0.0001], [3.4627, 1.5179, 0.0004, 0.1992, -0.0004, 0.0016, 0.0], [3.5066999999999995, 1.5735, -0.0007, 0.2067, -0.0003, 0.0016, 0.0], [3.5576999999999996, 1.6303, -0.0002, 0.2143, -0.0001, 0.0016, 0.0], [3.6076999999999995, 1.6875, 0.0001, 0.2223, 0.0003, 0.0016, 0.0], [3.6576999999999993, 1.7451, -0.0005, 0.23, 0.0004, 0.0017, 0.0], [3.7127, 1.8031, 0.0003, 0.2378, 0.0004, 0.0017, 0.0], [3.7586999999999993, 1.8617, 0.0007, 0.2457, 0.0001, 0.0017, -0.0001], [3.8087, 1.9207, 0.0, 0.2537, -0.0001, 0.0017, -0.0001], [3.8587, 1.9803, -0.0001, 0.2619, -0.0003, 0.0017, -0.0001], [3.9086999999999996, 2.0343, -0.0002, 0.2701, -0.0003, 0.0017, 0.0], [3.965699999999999, 2.0808, -0.0002, 0.2776, 0.0002, 0.0016, 0.0], [4.0097, 2.1277, 0.0, 0.2839, 0.0003, 0.0015, 0.0], [4.059699999999999, 2.1747, 0.0001, 0.2898, 0.0002, 0.0014, 0.0], [4.1107, 2.2218, 0.0006, 0.2957, -0.0004, 0.0013, -0.0001], [4.160699999999999, 2.2691, -0.0005, 0.3017, -0.0005, 0.0013, -0.0001], [4.2116999999999996, 2.3164, -0.0009, 0.3078, 0.0, 0.0012, 0.0], [4.2627, 2.3636, -0.0003, 0.3141, 0.0005, 0.0012, 0.0], [4.3126999999999995, 2.4116, 0.0001, 0.3206, 0.0003, 0.0012, 0.0], [4.362699999999999, 2.4594, 0.0002, 0.3271, 0.0001, 0.0012, 0.0], [4.4177, 2.5067, 0.0002, 0.3335, 0.0001, 0.0012, -0.0001], [4.463699999999999, 2.5306, 0.0004, 0.3397, -0.0003, 0.0011, -0.0001], [4.5146999999999995, 2.543, 0.0, 0.3432, -0.0003, 0.0009, -0.0001], [4.564699999999999, 2.5571, -0.0004, 0.3438, -0.0001, 0.0006, 0.0], [4.614699999999999, 2.5722, -0.0008, 0.344, 0.0006, 0.0004, 0.0], [4.670699999999999, 2.588, 0.0001, 0.3442, 0.0001, 0.0003, 0.0], [4.715699999999999, 2.6047, 0.0005, 0.3451, -0.0003, 0.0002, -0.0001], [4.7657, 2.6221, 0.0008, 0.3466, -0.0004, 0.0001, -0.0001], [4.8157, 2.6414, -0.0005, 0.3486, -0.0003, 0.0001, -0.0001], [4.8667, 2.6637, -0.0001, 0.351, 0.0002, 0.0001, 0.0], [4.918699999999999, 2.6863, -0.0001, 0.354, 0.0001, 0.0001, 0.0], [4.9677, 2.7097, 0.0001, 0.3572, 0.0003, 0.0001, 0.0], [5.0177, 2.7335, 0.0001, 0.3606, 0.0002, 0.0001, -0.0001], [5.0687, 2.7577, 0.0002, 0.3639, 0.0001, 0.0002, -0.0001], [5.1187, 2.7823, 0.0001, 0.3673, -0.0002, 0.0002, -0.0001], [5.1697, 2.8074, 0.0008, 0.3706, -0.0004, 0.0002, -0.0001], [5.218699999999999, 2.8329, -0.0005, 0.374, -0.0003, 0.0002, -0.0001], [5.2707, 2.8588, -0.0008, 0.3775, 0.0002, 0.0001, 0.0], [5.327699999999999, 2.8852, -0.0006, 0.381, 0.0007, 0.0001, 0.0], [5.3767, 2.9122, 0.0002, 0.3845, 0.0005, 0.0001, 0.0], [5.4216999999999995, 2.9395, 0.0003, 0.3881, 0.0002, 0.0001, -0.0001], [5.471699999999999, 2.967, 0.0003, 0.3917, -0.0001, 0.0001, -0.0001], [5.521699999999999, 2.9949, 0.0008, 0.3953, -0.0002, 0.0001, -0.0001], [5.5717, 3.0231, 0.0005, 0.399, -0.0003, 0.0001, -0.0001], [5.622699999999999, 3.0516, 0.0001, 0.4028, -0.0002, 0.0001, -0.0001], [5.673699999999999, 3.0803, 0.0, 0.4065, -0.0001, 0.0001, -0.0001], [5.7246999999999995, 3.1099, 0.0, 0.4102, 0.0, 0.0, -0.0001], [5.774699999999999, 3.1399, 0.0006, 0.414, -0.0001, 0.0, -0.0001], [5.8267, 3.1698, 0.0, 0.4178, -0.0004, 0.0, -0.0001], [5.8847, 3.1997, 0.0, 0.4216, -0.0002, 0.0, -0.0001], [5.928699999999999, 3.23, 0.0, 0.4254, -0.0001, -0.0001, -0.0001], [5.979699999999999, 3.2616, 0.0, 0.4294, 0.0004, -0.0001, 0.0], [6.0386999999999995, 3.2934, -0.0007, 0.4334, 0.0004, -0.0001, 0.0], [6.0797, 3.3245, 0.001, 0.4373, 0.0002, -0.0001, -0.0001], [6.130699999999999, 3.3559, 0.0005, 0.4412, -0.0002, -0.0001, -0.0001], [6.1807, 3.3875, 0.0003, 0.4451, -0.0001, -0.0002, -0.0001], [6.2307, 3.4193, 0.0001, 0.4489, 0.0, -0.0002, -0.0001], [6.303699999999999, 3.4513, -0.0006, 0.4528, 0.0002, -0.0002, -0.0001], [6.3457, 3.4837, 0.0007, 0.4568, 0.0002, -0.0003, -0.0001], [6.3957, 3.5277, 0.0002, 0.4621, -0.0002, -0.0003, -0.0001], [6.4456999999999995, 3.5579, 0.0002, 0.4657, -0.0001, -0.0003, -0.0001], [6.4967, 3.5908, 0.0002, 0.4696, 0.0003, -0.0004, -0.0001], [6.5477, 3.6239, 0.0004, 0.4735, 0.0001, -0.0004, -0.0001], [6.596699999999999, 3.6574, 0.0002, 0.4775, -0.0003, -0.0004, -0.0002], [6.6476999999999995, 3.6913, 0.0003, 0.4816, -0.0002, -0.0005, -0.0001], [6.6977, 3.7269, -0.0004, 0.4854, 0.0003, -0.0005, -0.0001], [6.747699999999999, 3.7823, 0.001, 0.49, 0.0003, -0.0005, -0.0001], [6.798699999999999, 3.838, 0.0003, 0.4974, 0.0, -0.0004, -0.0001], [6.8487, 3.8944, 0.001, 0.506, -0.0003, -0.0003, -0.0002], [6.898699999999999, 3.9516, 0.0002, 0.5145, -0.0006, -0.0003, -0.0002], [6.9487, 4.0098, 0.0002, 0.5227, -0.0003, -0.0002, -0.0001], [7.003699999999999, 4.0686, -0.0009, 0.5307, 0.0001, -0.0002, -0.0001], [7.049699999999999, 4.1282, -0.0002, 0.5386, 0.0003, -0.0002, -0.0001], [7.0996999999999995, 4.1886, 0.0003, 0.5464, 0.0005, -0.0002, 0.0], [7.1497, 4.25, 0.0004, 0.5543, 0.0002, -0.0003, -0.0001], [7.2007, 4.3121, 0.0013, 0.5621, -0.0001, -0.0003, -0.0001], [7.251699999999999, 4.375, 0.0013, 0.57, -0.0007, -0.0003, -0.0002], [7.301699999999999, 4.3787, 0.0003, 0.5766, -0.0002, -0.0005, -0.0002], [7.3587, 4.3696, -0.0005, 0.5739, 0.0002, -0.0009, -0.0001], [7.4027, 4.3609, 0.0003, 0.5653, 0.0004, -0.0013, -0.0001], [7.4577, 4.3517, -0.0001, 0.5572, 0.0004, -0.0017, -0.0001], [7.503699999999999, 4.3419, 0.0005, 0.5506, 0.0006, -0.002, -0.0001], [7.5537, 4.3317, 0.0005, 0.5447, 0.0002, -0.0022, -0.0001], [7.603699999999999, 4.321, 0.0005, 0.539, -0.0002, -0.0024, -0.0002], [7.654699999999999, 4.3099, 0.0005, 0.5338, -0.0001, -0.0025, -0.0001], [7.718699999999999, 4.2983, 0.0004, 0.5287, -0.0002, -0.0027, -0.0001], [7.769699999999999, 4.2863, 0.0004, 0.5238, -0.0002, -0.0028, -0.0001], [7.8197, 4.2695, -0.0005, 0.517, -0.0004, -0.0029, -0.0002], [7.869699999999999, 4.2574, -0.0008, 0.5127, 0.0004, -0.003, -0.0001], [7.924699999999999, 4.2441, 0.0005, 0.5088, 0.0005, -0.0031, 0.0], [7.98
